Feature/event details
NIAEFEUP/website-niaefeup-frontend pull request #290
Opened 2024-09-13 17:53 UTC by MRita443

Closes #143 

Initial version of event details page.

# Screenshots

# Review checklist

- [ ] Contains enough appropriate tests
- [ ] Behavior is as expected
- [ ] Clean, well-structured code

2025-07-01 19:50 UTC, rubuy-74 requested changes
It looks very nice, there are only some small changes needed.

Nice work :tada:

2025-07-01 19:50 UTC, rubuy-74 commented on src/routes/(app)/events/[slug]/_components/carousel.svelte
> +      {#each Array(5) as _, i (i)}
why is this 5 and not the number of images related to the event?

2025-07-01 19:50 UTC, rubuy-74 commented on src/routes/(app)/events/[slug]/_components/carousel.svelte
> +<script lang="ts">
the buttons don't work for me (in desktop or mobile)

![image](https://github.com/user-attachments/assets/715cd7bd-cc12-429b-8c2a-162b28034c40)

2025-07-01 19:50 UTC, rubuy-74 commented on src/routes/(app)/events/[slug]/+page.svelte
> +<script>
Is this intended behavior for the page on mobile?

![image](https://github.com/user-attachments/assets/c36862f0-9cd1-4aba-998e-767a5e032377)

2025-07-01 19:50 UTC, rubuy-74 commented on src/routes/(app)/events/[slug]/_components/event-header.svelte
> +  let eventImage = 'https://picsum.photos/500/500';
isn't it possible to integrate images from the backend?

2025-07-01 19:50 UTC, rubuy-74 commented on src/routes/(app)/events/[slug]/_components/event-header.svelte
> +      <img class="rounded-lg" src={eventImage} width="250" height="250" alt={data.title} />
This is right

2025-07-01 19:50 UTC, rubuy-74 commented on src/routes/(app)/events/[slug]/+page.svelte
> +    <!-- <Tabs.Content value="respostas">Respostas</Tabs.Content> -->
That makes sense, removing dead code improves readability.

2025-07-14 00:17 UTC, RuiSoares333 commented on src/routes/(app)/events/[slug]/_components/event-header.svelte
> +  let eventImage = 'https://picsum.photos/500/500';
I'm actually not sure if it is possible as is.
The only images that come from the backend do not have a defined format. They are either from picsum or a [img_name].png that I'm not sure it exists.
I'd like to get some confirmation/help on that

2025-11-26 14:12 UTC, closed without merging