initial user info page
NIAEFEUP/website-niaefeup-frontend pull request #295
Opened 2024-11-16 19:24 UTC by peucastro

Closes #284

### **Changes Implemented:**  
- **User Info Page**: Implemented priority version with backend integration.  
- **New Components**: Added `IsActiveBadge` and `SocialMediaIcon` local components.  
- **Edit Button**: Created a global `EditButton` component.  
- **Error Page Enhancements**:  
  - Updated layout for better user experience.  
  - Added Storybook entry for the error page.  
- **Type Update**: Renamed `gitHub` to `github` in `TeamMember` type to match with backend.  

## Screenshots
Desktop version             |  Mobile version
:-------------------------:|:-------------------------:
![](https://github.com/user-attachments/assets/287cc287-e65e-499b-954d-a018cf5e4e70)  |  ![](https://github.com/user-attachments/assets/af5e4e4f-69ba-4b52-841a-667ba4747905)

# Review checklist

- [ ] Contains enough appropriate tests
- [ ] Behavior is as expected
- [ ] Clean, well-structured code

2025-01-08 17:58 UTC, rubuy-74 requested changes
Everything looks great, there are only small things that could be a little different. :smile:

2025-01-08 17:58 UTC, rubuy-74 commented on src/routes/(app)/user/[id]/+page.svelte
> +  async function getMember() {
Instead of directly making calling fetch in the page, you should use a load function in another file to load the data, as it is described in the documentation (https://svelte.dev/docs/kit/load).

2025-01-08 17:58 UTC, rubuy-74 commented on src/routes/(app)/user/[id]/+page.svelte
> +              {#if teamMember.github}
As we discussed, since this is used in a different place, it would be good to have it as a separated component because there could be more uses of this in the future.

2025-01-08 17:58 UTC, rubuy-74 commented on src/routes/(app)/user/[id]/+page.svelte
> +        {#if showErrorMessage}
This is something that could be handled globally on the website. Nothing wrong with this, but its something we can discuss in the next standup

2025-01-10 17:12 UTC, peucastro commented on src/routes/(app)/user/[id]/+page.svelte
> +  async function getMember() {
Thank you for providing the resources for these changes. I have applied the updates as suggested. Could you please review the changes and confirm if everything is correct?

2025-01-10 17:14 UTC, peucastro commented on src/routes/(app)/user/[id]/+page.svelte
> +        {#if showErrorMessage}
I totally agree. I have removed it for now, and we can discuss this further at the next meeting.

2025-01-26 17:12 UTC, peucastro commented on src/routes/(app)/user/[id]/+page.svelte
> +  async function getMember() {
Since we were not able to mock `PageData` at this page's Storybook, we've decided to keep the fetch function at the page file itself. Thus, I'll mark this as resolved.

2025-02-11 12:31 UTC, MRita443 requested changes
It's looking great! Nearly done, just small organizational and test things

2025-02-11 12:31 UTC, MRita443 commented on src/routes/(app)/user/[id]/+page.svelte
> +          </button>
Maybe you could use the `Button` component here for consistency? If you need you can add an optional `onClick` argument to it and pass a function. If you could also abstract `EditButton` into its own component it'd be great because it's used in a lot of pages!

2025-02-11 12:31 UTC, MRita443 commented on src/routes/(app)/user/[id]/+page.ts
> +  if (res.status != 200) error(res.status, 'User not found');
```suggestion
  if (!res.ok) error(res.status, 'User not found');
```

2025-02-11 12:31 UTC, MRita443 commented on src/routes/(app)/user/_components/social-media-icon.stories.ts
There should be at least one example here that uses `iconPath`

2025-02-11 12:31 UTC, MRita443 commented on src/routes/(app)/+error.svelte
(A little out of scope of this PR but) could you add this page to storybook too?

2025-02-11 15:05 UTC, peucastro commented on src/routes/(app)/user/[id]/+page.svelte
> +          </button>
Wouldn't it be better if, instead of creating a new component, we modify the existing `Button` so it can receive an image as a parameter? Creating a new component just for the `EditButton` seems a little redundant, since most of the logic would be extracted from the `Button` component anyway. Alternatively, we could create a new button component that receives just images, not text. Which option do you think it's better?

2025-02-11 15:57 UTC, peucastro commented on src/routes/(app)/+error.svelte
I was trying to add it now, but since Storybook doesn't support the `$app/stores` module natively, it can get a little bit tricky to implement this. Instead of loading the error page, it just displays an internal error (due to the bad http status). I've tried using MSW to bypass this but couldn't get it to work. We can discuss this better at tomorrow's meeting!

2025-02-12 17:07 UTC, peucastro commented on src/routes/(app)/+error.svelte
Try to use sveltekit_experimental mock such as in #303

2025-02-17 19:21 UTC, MRita443 commented on src/routes/(app)/user/[id]/+page.svelte
> +          </button>
As we talked in the meeting (but just to immortalize here), yes you are absolutely right! But, as the edit button is used so many times throughout the design, I think it's worth it to guarantee that every page has the same consistent button and no slight changes in color, size or icon

2025-02-17 19:41 UTC, MRita443 approved these changes
Great job! This PR is great :) I left some small comments for if you still have patience but if not this is done and great as is already

2025-02-17 19:41 UTC, MRita443 commented on src/routes/(app)/user/[id]/+page.svelte
> +              {/if}
It'd be great if this could be a component too! I'd probably place it in `/user/_components` because it doesn't seem reusable in other pages at the moment but at least the logic is extracted and in storybook

2025-02-17 19:41 UTC, MRita443 commented on src/routes/(app)/user/[id]/+page.svelte
> +              {/if}
On that topic, I'd probably create a `src/lib/components/buttons` folder for organization too!

2025-02-17 19:41 UTC, MRita443 commented on src/lib/components/edit-button.stories.ts
> +  title: 'Atoms/Buttons/EditButton',
```suggestion
  title: 'Atoms/Buttons/Edit Button',
```

2025-02-17 22:59 UTC, peucastro commented on src/routes/(app)/user/[id]/+page.svelte
> +              {/if}
Thanks for the suggestions!

2025-02-18 17:23 UTC, rubuy-74 approved these changes
LGTM :rocket:

2025-02-18 17:23 UTC, merged